### ISSUE TITLE
后缀数组有一行可能越界

### ISSUE THREAD

**Issue by aLittleFat** [2014CAIS01/My-ACM-Template#2]
后缀数组第25行  for (int i = 0; i < m; i++) c[i] += c[i - 1]; 访问了c[i-1]，但是下标是从0开始的

**Comment by 2014CAIS01** [comment]
似乎是越界了，谢谢指出。不过由于 `maxn`一般不会开到正好的大小，所以越界一般都访问了t2数组中的无用的 0。
